services:
  spark-master:
    image: apache/spark-py:latest
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_USER=spark
      - HOME=/root
      - HADOOP_USER_NAME=root
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ..:/opt/spark/work-dir
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark-py:latest
    container_name: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_USER=spark
      - HADOOP_USER_NAME=root
      - SPARK_WORKER_DIR=/tmp/spark-work
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ..:/opt/spark/work-dir
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark-py:latest
    container_name: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_USER=spark
      - HADOOP_USER_NAME=root
      - SPARK_WORKER_DIR=/tmp/spark-work
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    volumes:
      - ..:/opt/spark/work-dir
    networks:
      - spark-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=spark
      - POSTGRES_PASSWORD=spark
      - POSTGRES_DB=sparkdb
    ports:
      - "5432:5432"
    volumes:
      - ../sql:/sql
      - ../data:/data
      - postgres-data:/var/lib/postgresql
    networks:
      - spark-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../mongo:/mongo
      - ../data:/data
      - mongo-data:/data/db
    networks:
      - spark-net

volumes:
  postgres-data:
  mongo-data:

networks:
  spark-net:
    driver: bridge
