-- Run against the data_engineering database.
-- Creates the zip_codes table (if absent) and loads it from the deluxe CSV.

CREATE TABLE IF NOT EXISTS zip_codes (
    ZipCode                     TEXT,
    PrimaryRecord               TEXT,
    Population                  TEXT,
    HouseholdsPerZipCode        TEXT,
    WhitePopulation             TEXT,
    BlackPopulation             TEXT,
    HispanicPopulation          TEXT,
    AsianPopulation             TEXT,
    HawaiianPopulation          TEXT,
    IndianPopulation            TEXT,
    OtherPopulation             TEXT,
    MalePopulation              TEXT,
    FemalePopulation            TEXT,
    PersonsPerHousehold         TEXT,
    AverageHouseValue           TEXT,
    IncomePerHousehold          TEXT,
    MedianAge                   TEXT,
    MedianAgeMale               TEXT,
    MedianAgeFemale             TEXT,
    Latitude                    TEXT,
    Longitude                   TEXT,
    Elevation                   TEXT,
    State                       TEXT,
    StateFullName               TEXT,
    CityType                    TEXT,
    CityAliasAbbreviation       TEXT,
    AreaCode                    TEXT,
    City                        TEXT,
    CityAliasName               TEXT,
    County                      TEXT,
    CountyFIPS                  TEXT,
    StateFIPS                   TEXT,
    TimeZone                    TEXT,
    DayLightSaving              TEXT,
    MSA                         TEXT,
    PMSA                        TEXT,
    CSA                         TEXT,
    CBSA                        TEXT,
    CBSA_Div                    TEXT,
    CBSA_Type                   TEXT,
    CBSA_Name                   TEXT,
    MSA_Name                    TEXT,
    PMSA_Name                   TEXT,
    Region                      TEXT,
    Division                    TEXT,
    MailingName                 TEXT,
    NumberOfBusinesses          TEXT,
    NumberOfEmployees           TEXT,
    BusinessFirstQuarterPayroll TEXT,
    BusinessAnnualPayroll       TEXT,
    BusinessEmploymentFlag      TEXT,
    GrowthRank                  TEXT,
    GrowingCountiesA            TEXT,
    GrowingCountiesB            TEXT,
    GrowthIncreaseNumber        TEXT,
    GrowthIncreasePercentage    TEXT,
    CBSAPopulation              TEXT,
    CBSADivisionPopulation      TEXT,
    CongressionalDistrict       TEXT,
    CongressionalLandArea       TEXT,
    DeliveryResidential         TEXT,
    DeliveryBusiness            TEXT,
    DeliveryTotal               TEXT,
    PreferredLastLineKey        TEXT,
    ClassificationCode          TEXT,
    MultiCounty                 TEXT,
    CSAName                     TEXT,
    CBSA_Div_Name               TEXT,
    CityStateKey                TEXT,
    PopulationEstimate          TEXT,
    LandArea                    TEXT,
    WaterArea                   TEXT,
    CityAliasCode               TEXT,
    CityMixedCase               TEXT,
    CityAliasMixedCase          TEXT,
    BoxCount                    TEXT,
    SFDU                        TEXT,
    MFDU                        TEXT,
    StateANSI                   TEXT,
    CountyANSI                  TEXT,
    ZIPIntroDate                TEXT,
    AliasIntroDate              TEXT,
    FacilityCode                TEXT,
    CityDeliveryIndicator       TEXT,
    CarrierRouteRateSortation   TEXT,
    FinanceNumber               TEXT,
    UniqueZIPName               TEXT,
    SSAStateCountyCode          TEXT,
    MedicareCBSACode            TEXT,
    MedicareCBSAName            TEXT,
    MedicareCBSAType            TEXT,
    MarketRatingAreaID          TEXT,
    CountyMixedCase             TEXT
);

-- Only load if the table is currently empty, so re-running is idempotent.
\set csv_path '/data/zip-codes-db.csv'

SELECT 'COPY zip_codes FROM ' || quote_literal(:'csv_path') ||
       ' WITH (FORMAT csv, HEADER true)'
WHERE NOT EXISTS (SELECT 1 FROM zip_codes LIMIT 1)\gexec
